version: '3.3'

services: 
  owncloud:
    image: owncloud:10.0.3
    volumes: 
      - "$PWD/index:/var/www/html"
    ports: 
      - 80:80
  mysql:
    image: mysql:5.7
    environment:
      - .env
    volumes: 
      - "$PWD/mysql_data:/var/lib/mysql"
